### ISSUE TITLE
Feature Request: Parallel Coordinates Graph

### ISSUE THREAD

**Issue by psarras** [XCharts-Team/XCharts#103]
This graph can be used instead of Radial Graph when parameters become more that 5. 
It is common to add the ability to "filter" results based on a domain within each axis and interactively reduce the number of lines.

![image](https://user-images.githubusercontent.com/3820417/99284898-bc701200-282e-11eb-9120-3efda81ba8a9.png)
![image](https://user-images.githubusercontent.com/3820417/99285231-330d0f80-282f-11eb-9acf-af8d25e2e443.png)

**Comment by monitor1394** [comment]
There are no plans for this at the moment, it is likely to be supported in version 2.0 in a few months.

**Comment by psarras** [comment]
@monitor1394 Is there a roadmap? I tried your plugin in a project already and it looks pretty sweet.

**Comment by monitor1394** [comment]
ParallelChart is supported in XCharts3.0.
But it looks like this feature is coming a little late.
