### ISSUE TITLE
关于柱状图

### ISSUE THREAD

**Issue by 1539303081** [XCharts-Team/XCharts#133]
大佬，为什么我在使用柱状图时，y轴可以绑定数据，而x轴却绑定不了，只能把XAxis0的Type改为Category才可以添加柱状图，XAxis0的Type改为Value却不行？

**Comment by monitor1394** [comment]
柱状图一般是x轴为类目轴y轴为数值轴。你想两个都是数值轴是要表达什么效果？有效果图吗？

**Comment by 1539303081** [comment]
就是把折线图转换为柱状图的形式，xy都是值来表示，折线图和柱状图同时显示。

**Comment by monitor1394** [comment]
XCharts3.0已支持。

**Comment by 1539303081** [comment]
谢谢大佬

**Comment by 1539303081** [comment]
我今天下载了XChart3.0，在折线图中添加Line时会出现报错，Unity2019.3.2f1和Unity2020.2.6f1都会出现错误
<img width="978" alt="微信截图_20220328103726" src="https://user-images.githubusercontent.com/50005166/160317076-506ff3d6-5762-4797-a3d9-e94673d3043f.png">
<img width="829" alt="微信截图_20220328103705" src="https://user-images.githubusercontent.com/50005166/160317083-a1c38cd0-1b38-4e93-aa85-1bb22e63a5b2.png">

**Comment by monitor1394** [comment]
感谢反馈，master修复了。
