### ISSUE TITLE
LiquidChart

### ISSUE THREAD

**Issue by yangyuang5451316465** [XCharts-Team/XCharts#177]
![6d7c83bde476a67d7435fc72856000e](https://user-images.githubusercontent.com/88355620/146147057-c658cd22-3b3b-4947-84ac-1473bf7c4eb2.png)

**Comment by monitor1394** [comment]
<img width="301" alt="image" src="https://user-images.githubusercontent.com/1450329/163524071-eecbec1d-56ff-48cd-b197-44ec6ebbcd77.png">

XCharts3.0的扩展图表水位图已支持圆角矩形，2.0版本不考虑支持。
