### ISSUE TITLE
Support for New Input System?

### ISSUE THREAD

**Issue by noirb** [XCharts-Team/XCharts#179]
Are there plans to support the [New Input System](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.0/manual/index.html) in the future?

**Comment by monitor1394** [comment]
Thank you for your suggestion. I will consider whether it can be supported in version 3.0.

**Comment by monitor1394** [comment]
New Input System is supported in [v3.6.0](https://github.com/XCharts-Team/XCharts/releases/tag/v3.6.0).
