### ISSUE TITLE
柱狀圖同柱顯示資料顯示

### ISSUE THREAD

**Issue by tbr77662** [XCharts-Team/XCharts#180]
在柱狀圖中將barGap設為-1可同柱顯示，第一組的資料大於第二組的資料可顯示2種顏色的柱狀，但如果第一組的資料小於第二組的資料會被擋住，可否重疊顯示2種顏色的柱狀

**Comment by Bian-Sh** [comment]
收到

**Comment by monitor1394** [comment]
> 

不好处理，每个serie都有对应的graphic来绘制，也就是所在层是固定的。可以考虑用设置半透明颜色来实现。

**Comment by monitor1394** [comment]
不考虑在Bar里支持这个。有需要的话可以考虑自己实现或者定制。
