### ISSUE TITLE
Determine the type of script on the object and how do I modify the chart type（判断物体上所挂载的脚本是哪一种Chart,并且如何利用脚本动态修改不同的Chart脚本）

### ISSUE THREAD

**Issue by ConanGentleman** [XCharts-Team/XCharts#185]
I wonder what type of chart is mounted on the object, I can only judge one by one, just like **tryGetComponent _< ScatterChart >()_** or **tryGetComponent _< LineChart >_ ();**  and so on. Is there a better way? I didn't see a way to solve it in the manual。In addition, I wanted to change the chart dynamically to different type, such as from ScatterChart to PieChart. I tried to delete the original _ScatterChart_ in _C#_ and then add the _PieChart_ , but it seemed that the _ScatterChart_ could not be deleted

我想知道对象上挂载的是什么类型的Chart，我只能逐个判断，就像 **tryGetComponent _< ScatterChart >()_** or **tryGetComponent _< LineChart >_ ();** 等等。有没有更好的办法?我在手册里找不到解决的办法。此外，我还想动态修改图表为不同的种类，例如从 **_ScatterChart_** 修改为 **_PieChart_** ，我尝试在 **_C#_** 中先删除原有的 **_ScatterChart_** 再添加 **_PieChart_** ，但似乎 **_ScatterChart_** 并不能被删除

**Comment by monitor1394** [comment]
这两个都不算是XCharts的问题。
你要判断是什么类型只能自己获取组件判断了；PieChart之类的也是MonoBehaviour，都是可以删除的。
