### ISSUE TITLE
关于使用TextMeshPro的问题

### ISSUE THREAD

**Issue by SteviePhang** [XCharts-Team/XCharts#194]
导入XChart后按照教程导入TextMeshPro，启动TextMeshPro，设置好字体，OK没问题。然后bug如下：
我删除了XChart然后重新导入，就报如下错，说找不到引用，但是TextMeshPro包明明还在
<img width="1821" alt="微信图片_20220424161341" src="https://user-images.githubusercontent.com/30717343/164966965-e95edcfc-6772-4005-a1c1-b5c34279d752.png">

**Comment by SteviePhang** [comment]
而且不管我导入哪个版本的XChart，都会报这个错，这个工程的XChart根本就没法使用了。只能重新新建工程

**Comment by monitor1394** [comment]
这个算不上bug，是本地XCharts的asmdef在更新版本时被覆盖了，丢掉了TMP的引用，所以报错。
需要自己手动修复：
方案一是自己改XCharts 的 asmdef ，加上 TextMeshPro 的引用
方案二是去掉 Project Setting 的宏 dUI_TextMeshPro，去掉后就是无TMP，更新完后再开回来

**Comment by LuchenyuHenry** [comment]
"references": [
         "Unity.TextMeshPro"
         ]
