### ISSUE TITLE
柱状图调整y轴范围时绘制有问题

### ISSUE THREAD

**Issue by zhangjialu** [XCharts-Team/XCharts#196]
操作：修改MinMaxTyp为Custom，调整min和max
![修改前](https://user-images.githubusercontent.com/20961154/165431423-315520f0-a7bf-417f-b812-0de0d260dff0.PNG)
![修改后](https://user-images.githubusercontent.com/20961154/165431445-f5feac0f-5518-4895-a6a8-39d0cd4f2310.PNG)

**Comment by monitor1394** [comment]
你是要5以下的就不绘制了是吧

**Comment by zhangjialu** [comment]
> 你是要5以下的就不绘制了是吧

是的，y轴最小值以下的不要画出来，另外比例也有问题，第一个柱子的y值是10，调整了y轴最小值为5时，第一个柱子直接就跑到x轴下面了，好像有个2倍的关系

**Comment by monitor1394** [comment]
master已处理，需要开启clip。
