### ISSUE TITLE
XCharts3.0的LineChart支持虚线

### ISSUE THREAD

**Issue by AiUWei** [XCharts-Team/XCharts#197]
Xchart3.0版本linechart里的LineType并没有虚线设置可以选择，LineStyle里的设置也没用。请问大家3.0版本虚线图表怎么用

**Comment by monitor1394** [comment]
3.0的虚线还在开发中

**Comment by monitor1394** [comment]
master上除了smooth外，其他情况已支持虚线。通过LineStyle的Type设置。

**Comment by AiUWei** [comment]
好的
