### ISSUE TITLE
基于UPM兼容性考虑，建议不要通过 *.unitypackage方式发布资源

### ISSUE THREAD

**Issue by SeanNi1221** [XCharts-Team/XCharts#199]
.unitypackage 中的文件将自动导入至 Assets/ 路径，该路径下的 package.json 无法被 Unity Package Manager 识别，从而给项目依赖关系管理造成困扰。
建议将 package.json 所在文件夹命名为 com.monitor1394.xcharts 并打包发布，用户下载后将该文件夹拖入 <YourProject>/Packages/ 路径下即可被 Unity Package Manager 自动识别为嵌入包。

**Comment by monitor1394** [comment]
XCharts需要兼容5.7以上版本，对于无UMP的Unity版本，用unitypackage的方式发布是合适的；对于需要package方式安装的项目，可以下载源码包，把里面的XCharts放到Packages下也是一样的。并且现在XCharts3.0的仓库就是一个package仓库。
