### ISSUE TITLE
Feature Request: TMP支持-增加自定义 Sprite Asset 功能

### ISSUE THREAD

**Issue by SeanNi1221** [XCharts-Team/XCharts#201]
TMP 的 Sprite Asset 功能可以快捷地在文本行内显示图像符号。
[https://docs.unity3d.com/Packages/com.unity.textmeshpro@3.2/manual/Sprites.html](参考)
目前Xcharts已经能够支持使用 TMP的 全局 Default Sprite Asset，希望增加像 TMP_Text Component 一样支持单独指定 Sprite Asset 的功能。

**Comment by monitor1394** [comment]
v3.1.0版本已处理。
