### ISSUE TITLE
在3.0中存在DataZoom缩放过后，Tooltip的数据跟图表对不上的问题。

### ISSUE THREAD

**Issue by ProjectLion** [XCharts-Team/XCharts#203]
DataZoom过滤模式切为None还是没用，2.0中不存在该问题。
![image](https://user-images.githubusercontent.com/22722232/175480673-b4dafec1-9225-4d9d-96e4-3e84b9214e66.png)
![image](https://user-images.githubusercontent.com/22722232/175480694-b529b2b0-598b-48de-8f73-008f22c3dc77.png)
![image](https://user-images.githubusercontent.com/22722232/175480707-2cfb5bfa-0546-4da3-9d6c-83a412e74b0a.png)

**Comment by monitor1394** [comment]
v3.1.0版本已处理。
