### ISSUE TITLE
BarChart在XY轴调换以及勾选Serie→More→PlaceHolder的情况下会一直提示 Invalid AABB inAABB

### ISSUE THREAD

**Issue by 15622162922** [XCharts-Team/XCharts#204]

**Comment by 15622162922** [comment]
![1656063544937](https://user-images.githubusercontent.com/49612681/175508797-ac759e19-be42-437f-9c43-f39c29d9503a.png)
![1656063556695](https://user-images.githubusercontent.com/49612681/175508832-6bc9454c-493b-4524-9ff0-084fba8c9cae.png)

**Comment by monitor1394** [comment]
看看是怎么重现的？我测试了没能重现出来。

**Comment by 15622162922** [comment]
![image](https://user-images.githubusercontent.com/49612681/175761865-db126713-644d-475c-a29b-3eb3589f4cd6.png)
![image](https://user-images.githubusercontent.com/49612681/175761867-3b58a9d8-c784-444b-9333-5ab9aada26e2.png)
![image](https://user-images.githubusercontent.com/49612681/175761876-205fa6ca-8197-47ee-b0bf-17cb7e9329fe.png)
![image](https://user-images.githubusercontent.com/49612681/175761882-76c43407-b9c1-43a6-94c4-b50c79483983.png)
主要的设置在这里了 
代码里是这样添加数据的
`for k, v in pairs(buffDatas) do
        local str = v.name.."\n作用目标：".. self:GetHeroName(v.targetId, self.battleIndex)..string.format("\n第%s秒 - 第%s秒",v.startTime, v.endTime)
        self.Obj_DetailBar:AddLimitData(str, v.startTime, v.endTime, "第"..v.startTime.."秒", "第"..v.endTime.."秒")
    end`

`public void AddLimitData(string name, float minValue, float maxValue, string minStr, string maxStr)
    {
        float during = maxValue - minValue;
        chart.AddXAxisData(minStr);
        chart.AddXAxisData(maxStr);
        chart.AddData(0, minValue, name);
        chart.AddData(1, during, name);
    }`

**Comment by 15622162922** [comment]
版本具体是v3.0.0-20220601

**Comment by monitor1394** [comment]
目前要求类目轴是必须要有数据的，就是YAxis的data需要有和serie个数一致的数据
