### ISSUE TITLE
如何控制linechart中的Toupltip 自动移动？想做一个播放功能。实时显示播放帧重的关键数据。不想用心电图的模式。

### ISSUE THREAD

**Issue by Stanlay19** [XCharts-Team/XCharts#208]
如何控制linechart中的Toupltip 自动移动？想做一个播放功能。实时显示播放帧重的关键数据。不想用心电图的模式。

**Comment by monitor1394** [comment]
需要自己写代码实现。主要还是看你的具体需求。
比如可以设置tooltip的AlwayShowContent为true，动态调整FixedX就可以实现水平方向移动。
