### ISSUE TITLE
调整坐标轴的Offset时,对应Axis Tick无法正确对齐相应轴

### ISSUE THREAD

**Issue by A1ian** [XCharts-Team/XCharts#209]
调整X或Y Axis的Offset值 移动轴的位置时，其对应的Axis Tick移动幅度大于轴移动的幅度，导致Tick无法保持在Axis上
在2.3.0版本内进行同样测试未发现该问题
且该问题内Axis Tick移动幅度约为X/YAxis Offset移动幅度的2倍

**Comment by A1ian** [comment]
![20220704104821](https://user-images.githubusercontent.com/39560828/177073665-affac466-1191-4eba-aaeb-e3b53bdb7a1b.jpg)

**Comment by monitor1394** [comment]
v3.1.0版本已处理。
