### ISSUE TITLE
在双坐标系下同时添加Bar和Line的Serie，如果Bar是横向（x轴Type为Value，y轴为Category），则line的显示会发生错误

### ISSUE THREAD

**Issue by 15622162922** [XCharts-Team/XCharts#210]
![image](https://user-images.githubusercontent.com/49612681/177075107-9f96e10b-78bf-4125-a222-0f1f8205a0cd.png)
![image](https://user-images.githubusercontent.com/49612681/177075138-717c37c9-a1d6-4759-ba01-3e443be78a14.png)
![image](https://user-images.githubusercontent.com/49612681/177075179-920927d9-2a77-453a-9609-6622ca766ec0.png)
![image](https://user-images.githubusercontent.com/49612681/177075273-d46f4552-10b1-4591-beef-4f923d66298f.png)
![image](https://user-images.githubusercontent.com/49612681/177075305-ff1eef78-2d3a-4db1-9906-2ce31c414f32.png)

**Comment by monitor1394** [comment]
v3.1.0版本已处理。
