### ISSUE TITLE
能否使用多线程模式

### ISSUE THREAD

**Issue by gawinwong** [XCharts-Team/XCharts#211]
每一帧的BaseChart.Update()需要消耗3ms，在同一帧中绘制13个图就需要40ms了，这样帧率就只有25，有没有办法使用多线程模式减少一帧的耗时

**Comment by monitor1394** [comment]
基本无法使用多线程。
先分析具体消耗在哪里。消耗和数据量、设置、图表类型有关，具体问题具体分析。

**Comment by gawinwong** [comment]
请问有哪些设置可以减少消耗，我使用的都是LineChart类型。

**Comment by monitor1394** [comment]
请给出具体的profiler数据。

**Comment by gawinwong** [comment]
![image](https://user-images.githubusercontent.com/13494956/177450978-448543d7-f79b-42d3-b699-aff9ff3cc285.png)
每次chart update都差不多这个耗时，我现在排查下来是ClearData()这个函数导致的。即使我没有使用AddData添加数据，只在每帧使用ClearData()都会是这个耗时。

**Comment by monitor1394** [comment]
为什么会每帧都调用ClearData()呢
ClearData()会触发Axis的重新初始化

**Comment by gawinwong** [comment]
AddXAxisData这个函数也会消耗1.5ms左右，有什么优化的方法吗

**Comment by monitor1394** [comment]
每帧都重新添加数据的方式不可用取，建议优化下写法。
