### ISSUE TITLE
动态生成图表的时候，第一次可以画出来，第二次画的时候存在偶尔画不出tooltip，需要调用RefreshAllComponent（）才能画出来

### ISSUE THREAD

**Issue by AGXR88** [XCharts-Team/XCharts#212]

**Comment by AGXR88** [comment]
![image](https://user-images.githubusercontent.com/69944034/177148900-cb9c9ba4-2b90-4bad-99ac-acefb1ab2f00.png)

**Comment by AGXR88** [comment]
![image](https://user-images.githubusercontent.com/69944034/177149030-aa7856a9-a8a5-40e4-b54f-132984b4554e.png)

**Comment by AGXR88** [comment]
![image](https://user-images.githubusercontent.com/69944034/177149086-762a4704-13f5-40a0-b0f9-7d70ccc2a067.png)

**Comment by monitor1394** [comment]
无法重现。master分支提交了Example_DynamicChart.cs测试例子，可以的话在这里例子的基础上重现一下看看。
