### ISSUE TITLE
鼠标移动到ToolTip 上时 会闪烁

### ISSUE THREAD

**Issue by wh-1219** [XCharts-Team/XCharts#213]
![x-chart](https://user-images.githubusercontent.com/56632571/177710842-c4f06912-6b57-4614-bcb6-5218968b52d0.gif)
鼠标移动到ToolTip 上时会ToolTip 会闪烁。

**Comment by monitor1394** [comment]
给上下文或者代码。
是否一直再刷新数据？

**Comment by wh-1219** [comment]
并没有动态刷新数据，随便创建一个折线图。鼠标移动到Tooltip 上就不停会闪烁。

**Comment by wh-1219** [comment]
> 给时间或代码。 是否一直在刷新数据？

并没有动态的刷新数据。随便创建一个折线图，鼠标来回移动到ToolTip 上就会闪烁。3.10 的版本还存在这个问题。

**Comment by monitor1394** [comment]
加Q群给测试工程吧

**Comment by monitor1394** [comment]
新建工程，创建默认的LineChart看看，排查干扰。
如果新工程没问题，看看自己的工程是否有其他逻辑触发了界面刷新。
