### ISSUE TITLE
导入后启用textmeshpro出现报错，使用XCharts-3.0.1，Editor版本2021.3.4f1c1

### ISSUE THREAD

**Issue by ysms2022** [XCharts-Team/XCharts#214]
启用后报出的错误如下：
Assets\3rd-Party\XCharts\Runtime\Component\Child\TextStyle.cs(152,37): error CS0102: The type 'TextStyle' already contains a definition for 'tmpFontStyle'
尝试修改后，错误消失，但textmeshpro并没有正常工作。点击”Rebuild Chart Object“按钮后并没有反应。依然无法正常工作。

**Comment by monitor1394** [comment]
v3.1.0版本已处理。TextMeshPro用法可查看教程。
