### ISSUE TITLE
柱状图-横向-动态新增Bar会显示异常。

### ISSUE THREAD

**Issue by wh-1219** [XCharts-Team/XCharts#216]
![20220722165346](https://user-images.githubusercontent.com/56632571/180402735-401c8db7-c183-4355-88a0-10c697397d28.png)
AddSerie->Bar

**Comment by wh-1219** [comment]
![20220722170627](https://user-images.githubusercontent.com/56632571/180405289-0e581f81-f544-4d83-8cbd-3dfa4b5b0a5d.png)
Cover XY Axis , 清除Serie列表，重新创建两条柱子后会只显示一条，并且显示错误。

**Comment by monitor1394** [comment]
不算什么异常。
1. serie的数据和xy轴数据要保持一致。
2. 查看颜色透明度。

**Comment by wh-1219** [comment]
> 没什么异常。
> 
> 1. 系列的数据和 xy 轴数据要保持一致。
> 2. 查看颜色。
> 3. 人体发现保存。

    void Start()
    {
        chart = gameObject.GetComponent<BarChart>();
        InvokeRepeating("UpdateData", 1,5);
    }
    void UpdateData()
    {

        chart.ClearData();
        chart.series.Clear();
        for (int i = 0; i < 5; i++)
        {
            chart.AddYAxisData("y" + i);
        }
        for (int j = 0; j < 3; j++)
        {
            var serie = chart.AddSerie<Bar>(j.ToString());
            serie.showDataName = true;
            for (int i = 0; i < 5; i++)
            {
                chart.AddData(j, Random.Range(0, 200));
            }
        }
        chart.AnimationFadeIn();
    }
清除Serie后重新创建柱子出不来。

**Comment by monitor1394** [comment]
> > 没什么异常。
> > 
> > 1. 系列的数据和 xy 轴数据要保持一致。
> > 2. 查看颜色。
> > 3. 人体发现保存。
> 
> ```
> void Start()
> {
>     chart = gameObject.GetComponent<BarChart>();
>     InvokeRepeating("UpdateData", 1,5);
> }
> void UpdateData()
> {
> 
>     chart.ClearData();
>     chart.series.Clear();
>     for (int i = 0; i < 5; i++)
>     {
>         chart.AddYAxisData("y" + i);
>     }
>     for (int j = 0; j < 3; j++)
>     {
>         var serie = chart.AddSerie<Bar>(j.ToString());
>         serie.showDataName = true;
>         for (int i = 0; i < 5; i++)
>         {
>             chart.AddData(j, Random.Range(0, 200));
>         }
>     }
>     chart.AnimationFadeIn();
> }
> ```
> 
> 清除Serie后重新创建柱子出不来。

这个确认时有问题，动画播放异常了。下个版本修复。

**Comment by monitor1394** [comment]
你可以将:
`chart.ClearData();`
`chart.series.Clear();`
换为：
`chart.RemoveData();`

**Comment by monitor1394** [comment]
用chart.RemoveData()
如果只想移除serie，v3.2.0版本增加了新API：chart.RemoveAllSerie()，不要直接操作chart.series.Clear()
