### ISSUE TITLE
饼图锯齿严重

### ISSUE THREAD

**Issue by Rain624** [XCharts-Team/XCharts#220]
在都不开启抗锯齿的基础下，有的项目中饼图锯齿特别严重，有的项目正常，对比了两个项目无法找到造成锯齿的具体原因

**Comment by monitor1394** [comment]
看问答：16。

> 开启抗锯齿设置（在Unity里设置）。调整UI渲染模式为Camera模式，开启MSAA，设置4倍或更高抗锯齿。

主要是Canvas的渲染模式，需要选Camera。
