### ISSUE TITLE
DrawLine分断严重

### ISSUE THREAD

**Issue by Ander456** [XCharts-Team/XCharts#222]
![image](https://user-images.githubusercontent.com/20219696/187576037-47529be8-d7d0-45a0-bde3-4c53c086d11e.png)
RT，  UGL.DrawLine(vh, center, anchor, 1f, new Color32(175,135,4, 255));

**Comment by monitor1394** [comment]
和XCharts无关，做好相关的unity设置，比如抗锯齿

**Comment by Ander456** [comment]
抗锯齿开了 没有用 --- 这种情况在 两个点快到一条线上的时候 尤为明显。

**Comment by monitor1394** [comment]
https://github.com/XCharts-Team/XCharts-Demo
