### ISSUE TITLE
游戏暂停时，拆线图自带的刷新动画不运行，导致图表不显示

### ISSUE THREAD

**Issue by miblooming** [XCharts-Team/XCharts#223]
建议类似Unity自带的Animator，可以设置动画是基于Time.time或Time.unscaledTime来运行
这样，当游戏使用Time.timeScale=0来暂停游戏时，UI上的图表，仍可正常基于Time.unscaledTime来进行动画刷新显示

**Comment by monitor1394** [comment]
master分支已支持。
Animation增加了UnscaledTime参数：
<img width="412" alt="image" src="https://user-images.githubusercontent.com/1450329/195469158-ebc4f9c2-946e-4378-a408-d5256038e575.png">
勾选后设置Time Scale为0后动画依旧会播放。
图表刷新需要Update，在Unity2017.4上测试发现，当暂停游戏时Update也不运行了，所以图表也不会刷新。
