### ISSUE TITLE
請教Tooltip之Type設為Cross時兩Axis顯示的Label是由哪個formatter控制

### ISSUE THREAD

**Issue by s103062115** [XCharts-Team/XCharts#226]
XAxis的Type設為Time時Tooltip於XAxis上顯示的Label仍以Value方式呈現，想請教如何將其轉為DateTime方式呈現。
另外tooltip formatter的{b}，說明中表示{b}為顯示Serie Data Name，但實際只顯示空白，想請教用法是否正確。
![image](https://user-images.githubusercontent.com/17896089/195282778-344a1dd2-9974-4901-85e3-da10fdf173fb.png)
![image](https://user-images.githubusercontent.com/17896089/195282898-03ad2716-1228-4131-a8eb-2cd7e20534c8.png)

**Comment by monitor1394** [comment]
Cross的label目前确实还不支持自定义formatter。
{b}在坐标系下只会代表类目轴，此时可以用{e}显示dataName

**Comment by monitor1394** [comment]
<img width="478" alt="image" src="https://user-images.githubusercontent.com/1450329/198860044-62585f3a-e32f-46e5-8190-2e89803abdeb.png">
Axis下增加了indicatorLabel可单独设置每个Axis的Tooltip指示文本样式。
