### ISSUE TITLE
在柱状图使用透明渐变色时,tooltip数据项前的小圆点颜色也会变透明,如何解决

### ISSUE THREAD

**Issue by 2323623353** [XCharts-Team/XCharts#229]
![image](https://user-images.githubusercontent.com/63123942/196832925-3cfa0ade-ddc6-4644-91d8-3d50cf8c7c01.png)
Legend也是会变,不过可以手动指定颜色

**Comment by 2323623353** [comment]
![image](https://user-images.githubusercontent.com/63123942/196973059-34deb094-5511-4f23-be7b-e09d84e6d3e4.png)
在color中使用了完全透明

**Comment by monitor1394** [comment]
Legend和Tooltip显示的颜色取自itemstyle的color。color的透明可以改itemstyle的opacity，但也会同时影响toColor，确实有这个问题。
3.0版本color的透明度不影响legend，legend有itemAutoColor和itemOpacity。
你这种情况在目前版本下，可以通过itemstyle的itemFormatter自定义Tooltip显示的颜色，格式如下：
`<color=#000000>●</color>|{a}|{c}`
里面的颜色值即为你要显示的颜色值。

**Comment by 2323623353** [comment]
3.0按照这个格式自定义itemFormatter颜色还是会受到color透明度影响

**Comment by monitor1394** [comment]
都自定义了，不会受影响。发一下配置和效果图

**Comment by monitor1394** [comment]
颜色值用双引号“”
`<color=“#000000”>●</color>|{a}|{c}`

**Comment by monitor1394** [comment]
> 颜色值用双引号“” `<color=“#000000”>●</color>|{a}|{c}`

不过我测试的有没有双引号都正常，3.3.0版本

**Comment by 2323623353** [comment]
发现问题了,在我开启tmp的时候就会出现透明,关闭之后就是正常的

**Comment by monitor1394** [comment]
测试了下，TextMeshPro下富文本的颜色竟然会有受总颜色透明度的影响；UGUI的text用富文本时是没有影响的。
这个就不好改了。
