### ISSUE TITLE
在图表父物体使用Vertical Layout Group时,运行时label会不显示

### ISSUE THREAD

**Issue by 2323623353** [XCharts-Team/XCharts#231]
![image](https://user-images.githubusercontent.com/63123942/197151506-2fc1a729-b252-479b-95d4-d8d4c8456f89.png)
![image](https://user-images.githubusercontent.com/63123942/197151616-6ec5fe60-0e50-42f0-bbb1-d5e37403a2a4.png)
![image](https://user-images.githubusercontent.com/63123942/197151646-4dc692d5-cb32-4776-aafc-124c8bfcc191.png)

**Comment by monitor1394** [comment]
master已修复，晚点发release。
