### ISSUE TITLE
在webgl模式下 激活悬浮tootip 会报错

### ISSUE THREAD

**Issue by jeadongsun** [XCharts-Team/XCharts#236]
在webgl模式下 激活悬浮tootip 会报错

**Comment by monitor1394** [comment]
给一下具体信息

**Comment by Bian-Sh** [comment]
这个问题问的太没有诚意了
不说图文并茂吧，问题重现流程得有呀
xchart demo 就是 webgl 版本的啊，我体验着好像完全没有问题吧！
