### ISSUE TITLE
如何获取某ChildComponent组件？example中似乎没有提及

### ISSUE THREAD

**Issue by sunyrain** [XCharts-Team/XCharts#244]
如何获取组件themestyle，并将其transparentbackground设置为true？
（主要想问如何获取ChildComponent?）能大致给出代码吗？

**Comment by monitor1394** [comment]
theme和settings是常驻主组件，可以通过chart.theme和chart.settings来访问。
其他非必需主组件可通过chart.GetChartComponent<T>()接口来获取。

serie也分常驻子组件和额外子组件：
常驻组件可以直接serie.xxx来访问；
额外组件通过serie.AddExtraComponent<T>()来添加和获取。

serieData也类似：
通过serieData.GetOrAddComponent<T>()来获取额外组件。

**Comment by sunyrain** [comment]
十分感谢您的回答！所以说themetype及其他ChildComponent都属于非必须主组件，通过GetChartComponent（）来获取对吗？

从 Windows 版邮件发送

发件人: monitor1394
发送时间: 2023年2月8日 7:48
收件人: XCharts-Team/XCharts
抄送: sunyrain; Author
主题: Re: [XCharts-Team/XCharts] 如何获取某ChildComponent组件？example中似乎没有提及 (Issue #244)

theme和settings是常驻主组件，可以通过chart.theme和chart.settings来访问。
其他非必需主组件可通过chart.GetChartComponent()接口来获取。
serie也分常驻子组件和额外子组件：
常驻组件可以直接serie.xxx来访问；
额外组件通过serie.AddExtraComponent()来添加和获取。
serieData也类似：
通过serieData.GetOrAddComponent()来获取额外组件。

**Comment by sunyrain** [comment]
感谢您的回答！
