### ISSUE TITLE
Labels overlapping in ring charts

### ISSUE THREAD

**Issue by PowZone** [XCharts-Team/XCharts#247]
![image](https://user-images.githubusercontent.com/3472474/223877971-8f19d609-7b41-439f-a9d1-9521925ae21a.png)

Is it possible to avoid the overlap of labels?

**Comment by monitor1394** [comment]
Not supported yet. We will try to support it in the next version.

**Comment by monitor1394** [comment]
> ![image](https://user-images.githubusercontent.com/3472474/223877971-8f19d609-7b41-439f-a9d1-9521925ae21a.png)
> 
> Is it possible to avoid the overlap of labels?

What kind of effect do you want? Are there any screenshots？

**Comment by monitor1394** [comment]
Supported in v3.8.0
