### ISSUE TITLE
Tooltip取色问题

### ISSUE THREAD

**Issue by Ambitroc** [XCharts-Team/XCharts#249]
![image](https://user-images.githubusercontent.com/84306786/224877435-ad92761c-ccd4-4eba-9519-2a8e1ab25456.png)
![image](https://user-images.githubusercontent.com/84306786/224877478-59052db5-2eca-457d-96f4-4e8d4cdae450.png)
当ItemStyle颜色设置为透明到非透明渐变时，Tooltip会取到透明的颜色

**Comment by monitor1394** [comment]
设置markColor
