### ISSUE TITLE
Tooltip在两个Serie的时候显示有bug

### ISSUE THREAD

**Issue by lishuwei115** [XCharts-Team/XCharts#253]
两个Serie，Serie0是Bar,Serie1是Line，Serie0的XAxisIndex是0，YAxisIndex是0,Serie1的XAxisIndex是1,YAxisIndex是1，XAxis0的Type是Category，数量是5；XAxis1的Type是Category，数量是10，Tooltip显示的时候有bug。
![微信图片_20230412150320](https://user-images.githubusercontent.com/20329904/231378076-002d46e1-9d60-40ad-ac9a-34faa30644de.png)

**Comment by monitor1394** [comment]
这种情况Tooltip的Trigger用Item，没法用Axis
