### ISSUE TITLE
LineChart的Symbol不支持自定图片么？设置了没用~

### ISSUE THREAD

**Issue by ProjectLion** [XCharts-Team/XCharts#254]
<img width="226" alt="image" src="https://user-images.githubusercontent.com/22722232/234791724-9a0bac49-b2fe-4652-9765-700ce7fc9cbf.png">
<img width="712" alt="image" src="https://user-images.githubusercontent.com/22722232/234791759-aacd5c6e-5fde-4c71-a370-13005a002826.png">

**Comment by monitor1394** [comment]
symbol是用代码绘制的，不支持定义图片。这里是给象形主图用的。
想自定义图标可以用serie的label设置icon来代替。

**Comment by ProjectLion** [comment]
soga，我就说debug下看不到Image组件，感谢大佬解答。
