### ISSUE TITLE
多个折线图放到ScrollView中上下滚动时帧数暴跌，最多会跌到50% 200帧降到100帧。

### ISSUE THREAD

**Issue by ProjectLion** [XCharts-Team/XCharts#257]

**Comment by monitor1394** [comment]
ScrollView滚动会刷新UI，触发图表刷新，图表绘制是消耗性能的，降帧正常。看要刷新的图表数量，数据量，图表复杂度。

**Comment by ProjectLion** [comment]
每次刷新的图表在3-4个。图表就一个折线图，包含AreaStyle，每个图表数据量在300-600，这个数据量也不大啊~有没有啥办法能解决？
