### ISSUE TITLE
The legend of the pie chart shows an exception

### ISSUE THREAD

**Issue by LiuHT96** [XCharts-Team/XCharts#278]
When the pie chart is refilled with data, the percentage of the legend shows an exception

**Comment by monitor1394** [comment]
Can you give us more information?
XCharts version, data, exception detail and screenshots.

**Comment by LiuHT96** [comment]
v3.8.0 use Example31_PieUpdateName When I use a space to trigger the ClearAndAddData method, the legend above the graph shows a percentage exception。

**Comment by monitor1394** [comment]
The master branch has been fixed.
