### ISSUE TITLE
ToolTip组件报错

### ISSUE THREAD

**Issue by Ambitroc** [XCharts-Team/XCharts#279]
当类目轴数据为空时，鼠标移入图表内，tooltip报错。
初步判断是触发tooltip画轴线计算时出现异常，报错和错误大致位置如下图。
![Snipaste_2023-09-15_15-09-37](https://github.com/XCharts-Team/XCharts/assets/84306786/1137d85e-6813-40c1-9f82-713036eb8bba)
![Snipaste_2023-09-15_15-10-48](https://github.com/XCharts-Team/XCharts/assets/84306786/e39f6d55-c6df-411e-8306-326d0fdf6e1b)

**Comment by monitor1394** [comment]
master分支已修复
