### ISSUE TITLE
饼图存在aabb那个bug

### ISSUE THREAD

**Issue by li-qxzl** [XCharts-Team/XCharts#282]
用的是3.8.1的包，经测试，饼图在Start()函数内如果调用ClearData()，unity会报“Invalid AABB inAABB”，另外也与饼图的animation -> Addition的选项有关，若去掉勾选不会报错，勾上并在Start()函数内调用ClearData会报错

**Comment by monitor1394** [comment]
用最新master测试没发现有此问题
