### ISSUE TITLE
The document is not in English after switching to English view.

### ISSUE THREAD

**Issue by VeyronSakai** [XCharts-Team/XCharts#283]
The document was not in English even after switching to English view.

I would very much appreciate it if you could correct it as I would love to read it in English.

<img width="600" alt="スクリーンショット 2023-10-18 22 02 12" src="https://github.com/XCharts-Team/XCharts/assets/43900255/e79c45f9-83d1-4d6d-8fff-ae9681a6b3c1">

**Comment by monitor1394** [comment]
OK, the English documentation is now supported. We will continue to improve it, and thank you for your support!

![docs-en](https://github.com/user-attachments/assets/e882958d-de38-4cb3-bf26-af270f78555e)
