### ISSUE TITLE
 onEnter   SerieEventData 事件 value 值一直是0

### ISSUE THREAD

**Issue by chen8153069** [XCharts-Team/XCharts#287]

**Comment by monitor1394** [comment]
麻烦给详情：什么图表？测试用例？

**Comment by chen8153069** [comment]
3.82 
![image](https://github.com/XCharts-Team/XCharts/assets/67939165/d56137b3-cfb5-4bae-a5ca-b3661d78f9b0)
案例 试了下  onEnte  在有Tooltip 下无法 触发应该是被遮挡。 值是0
