### ISSUE TITLE
AxisLabel missing {value} placeholder docs

### ISSUE THREAD

**Issue by cristianofromagio** [XCharts-Team/XCharts#291]
## Context
I was trying to suffix a string to the `XAxis` entries, so tried to use the `formatter` field on the `Axis Label`, in which none of the docs placeholders worked (it rendered the placeholder as a text).

![image](https://github.com/XCharts-Team/XCharts/assets/16294559/ee111809-1c58-4473-9de5-552f0a84bf24)

## Docs
I tried to find the `Axis Label` `formatter` placeholders values in the [Configuration docs](https://xcharts-team.github.io/docs/configuration):
- [`XAxis`](https://xcharts-team.github.io/docs/configuration#xaxis)
  + pointed to [`Axis`](https://xcharts-team.github.io/docs/configuration#axis)
  + [`Axis.axisLabel`](https://xcharts-team.github.io/docs/configuration#Axis-axisLabel)
    + pointed to [`AxisLabel`](https://xcharts-team.github.io/docs/configuration#axislabel)
    + [`AxisLabel`](https://xcharts-team.github.io/docs/configuration#axislabel) had no mention of a `formatter` so followed to [`LabelStyle`](https://xcharts-team.github.io/docs/configuration#labelstyle)
      + [`LabelStyle.formatter`](https://xcharts-team.github.io/docs/configuration#LabelStyle-formatter)

**Description for `LabelStyle.formatter` on the docs:**
> 标签内容字符串模版格式器。支持用 \n 换行。 模板变量有： {.}：圆点标记。 {a}：系列名。 {a}：系列名。 {b}：类目值或数据名。 {c}：数据值。 {d}：百分比。 {e}：数据名。 {f}：数据和。 示例：“{b}:{c}”

**Translated to english (it is also missing the placeholder values on the [english docs file](https://github.com/XCharts-Team/XCharts/blob/83db4dd951a572b2911c2f5a6bbac867b593694b/Documentation~/en/configuration.md?plain=1#L1228)):**
> Tag content string template formatter. Line breaks with \n are supported. Template variables are: {.}: dot mark. {a}: Series name. {a}: Series name. {b}: Category value or data name. {c}: data value. {d}: Percentage. {e}: data name. {f}: data sum. Example: "{b}:{c}"

## Solution
While searching the other `formatter` fields, the [`Legend.formatter`](https://xcharts-team.github.io/docs/configuration/#Legend-formatter) mentioned the `{value}` placeholder while also mentioning the template placeholders on `Tooltip.itemFormatter` (another related issue #290).

I tried using the `{value}` placeholder and it worked!

![image](https://github.com/XCharts-Team/XCharts/assets/16294559/49af7099-471c-4f5a-b2d6-efeae989737c)

I also found this information while searching the FAQ files, but the [english FAQ](https://github.com/XCharts-Team/XCharts/blob/83db4dd951a572b2911c2f5a6bbac867b593694b/Documentation~/en/faq.md?plain=1#L112) does not have the `AxisLabel` `formatter` description, which is present in the [chinese FAQ](https://github.com/XCharts-Team/XCharts/blob/83db4dd951a572b2911c2f5a6bbac867b593694b/Documentation~/zh/faq.md?plain=1#L116).

**From chinese FAQ file:**
> 如何让Y轴显示多位小数
> 答：设置`Axis`下的`AxisLabel`中的`formatter`为`{value:f1}`或`{value:f2}`。`1.5.0`及以上版本通过`numericFormatter`设置。

**Translated to english (it is missing the `formatter` segment on the english FAQ file):**
> How to make the Y axis display multiple decimal places
> Answer: Set the `formatter` in `AxisLabel` under `Axis` to `{value:f1}` or `{value:f2}`. Versions `1.5.0` and above are set via `numericFormatter`.

## Suggestion
It would be nice to have the template placeholders for the `AxisLabel` `formatter` mentioned in the FAQ also documented in the Configuration docs (namely the `{value}` placeholder) where applicable.

**Comment by monitor1394** [comment]
Very detailed description, thanks for feedback, we will improve the documentation as soon as possible.
