### ISSUE TITLE
大量堆叠柱状图效率问题

### ISSUE THREAD

**Issue by chen8153069** [XCharts-Team/XCharts#294]
我测试单创建400个柱状堆叠一起，帧数只能达到30，有啥办法提高效率？
![image](https://github.com/XCharts-Team/XCharts/assets/67939165/8349efe6-9629-4fac-8591-de62f19bc656)
![image](https://github.com/XCharts-Team/XCharts/assets/67939165/f31b74c2-fde5-49e0-b516-6fef5ee993cc)
![image](https://github.com/XCharts-Team/XCharts/assets/67939165/de9a348a-f810-4502-9330-5f7744455381)
![image](https://github.com/XCharts-Team/XCharts/assets/67939165/20c45837-4dd0-46d2-8f3b-0122cbbc7b9e)

**Comment by monitor1394** [comment]
一个chart里放了400多个serie？什么实际场景会用到这个需求？

**Comment by chen8153069** [comment]
按时间显示一些类型数值。也就一问。哈哈！

**Comment by monitor1394** [comment]
可以根据需求再自己看看怎么调整源码。一个chart超过几十个serie的时候，可能会有其他更佳的方案。
