### ISSUE TITLE
关于linechart的参数设置问题

### ISSUE THREAD

**Issue by zl880411** [XCharts-Team/XCharts#298]
XCHART_V3.9中的linechart如何设置areaStyle,目前组件的编辑面板中没有找到对应参数
![image](https://github.com/XCharts-Team/XCharts/assets/13516610/b05efe20-be7c-4795-ad52-7067a6310794)

需要实现如下效果：

![image](https://github.com/XCharts-Team/XCharts/assets/13516610/4d7f7d0a-07ef-4a15-ab6e-536d2abe127e)

目前只能完成线段的绘制，无法绘制阴影
![image](https://github.com/XCharts-Team/XCharts/assets/13516610/5167f437-8711-43ee-9a73-21a1d199dd9f)

**Comment by monitor1394** [comment]
首次使用3.x版本建议读一遍 [XCharts 教程：5分钟上手 XCharts](https://github.com/XCharts-Team/XCharts/blob/master/Documentation~/zh/tutorial01.md)
上面有提到如何给serie添加组件
