### ISSUE TITLE
Question: How to subscribe to DataZoom value changes?

### ISSUE THREAD

**Issue by HajiyevEl** [XCharts-Team/XCharts#314]
Hi again!
~When using DataZoom, how should i get currently displayed candlesticks data?~

I want to be able to set yAxis min-max values (Min-Max Type: Custom) depending on currently displayed min-max values of candlesticks on screen (from series data), and subscribe to OnDataZoomRangeChanged for further updates.
Tried using Min-Max Type: Auto, but it seems it gets min-max values from all serie data, not currently displayed (on-screen)

**Comment by HajiyevEl** [comment]
Alright, i found how to get data from DataZoom:
```c#
                chart.GetDataZoomOfSerie(serie, out DataZoom xDataZoom, out DataZoom yDataZoom);
                var dataList = serie.GetDataList(xDataZoom);
``` 
Now how i should subscribe to OnDataZoomRangeChanged for updates when zoom changes?

**Comment by monitor1394** [comment]
The `startEndFunction` of DataZoom is a callback for when the `start` and `end` values of a DataZoom change. You can try using this function.
