### ISSUE TITLE
Help with CandlestickChart GridLayout component required

### ISSUE THREAD

**Issue by HajiyevEl** [XCharts-Team/XCharts#316]
Hi again! Stumbled upon a problem when using GridLayout component on my CandlestickCharts. My charts are being squeezed/shrinked too much when adding rows. There are much of space for charts to stretch, but they are squeezed to top/bottom instead. How can i make them fit proportionally?

<details><summary>Screenshots</summary>
<p>

![Screenshot 2024-04-14 104531](https://github.com/XCharts-Team/XCharts/assets/70325881/023c299f-3e50-4da4-8b86-1ff0e055e5a5)
![Screenshot 2024-04-14 104549](https://github.com/XCharts-Team/XCharts/assets/70325881/d7ae5fb9-fba2-4a53-8ad1-1aa52cac1f24)

</p>
</details>

**Comment by HajiyevEl** [comment]
I think i know what caused this squeezing. When i change LayoutIndex in GridCoord from -1 to 0, padding of that GridCoord becomes hidden, BUT it still influences GridLayout padding. Actually, it's good thing, because user can set prefered sizes of charts from indexed GridCoord. It's just that i don't understand, why hide charts GridCoord padding, if it's still influences GridLayout?

<details><summary>Screenshots</summary>
<p>

![Screenshot 2024-04-14 164932](https://github.com/XCharts-Team/XCharts/assets/70325881/03af6322-5ce5-4c9e-8b4e-2b8053fe8597)
![Screenshot 2024-04-14 164937](https://github.com/XCharts-Team/XCharts/assets/70325881/5a737c46-affe-4fb9-ad82-0b7435b74f61)


</p>
</details>

**Comment by monitor1394** [comment]
OK, the master branch has been optimized so that the Left Right Top Bottom parameters are always displayed and no longer hidden when setting GridLayout.
