### ISSUE TITLE
Question: Multiple DataZooms interconnected

### ISSUE THREAD

**Issue by HajiyevEl** [XCharts-Team/XCharts#317]
Hi again!
Legend: I want to connect my charts so that when i zoom one of them, other charts also get zoomed. 

Problem: I have multiple charts in GridLayout and added DataZoom components for each of them, because in your code in BaseChart.Component.cs, you are setting grid of 0 indexed axis as main grid for DataZoom:
```c#
        public GridCoord GetGridOfDataZoom(DataZoom dataZoom)
        {
            GridCoord grid = null;
            if (dataZoom.xAxisIndexs != null && dataZoom.xAxisIndexs.Count > 0)
            {
                var xAxis = GetChartComponent<XAxis>(dataZoom.xAxisIndexs[0]);
                grid = GetChartComponent<GridCoord>(xAxis.gridIndex);
            }
            else if (dataZoom.yAxisIndexs != null && dataZoom.yAxisIndexs.Count > 0)
            {
                var yAxis = GetChartComponent<YAxis>(dataZoom.yAxisIndexs[0]);
                grid = GetChartComponent<GridCoord>(yAxis.gridIndex);
            }
            if (grid == null) return GetChartComponent<GridCoord>();
            else return grid;
        }
``` 
So, to make multiple charts interconnected, i need to add DataZoom component for each of them and set each chart's xAxis index as 0 index in list of dataZoom.xAxisIndexs of that DataZoom component to make it main. (Or so i think)
Now, what i have:
<details><summary>DataZooms Screenshots</summary>
<p>

![Screenshot 2024-04-14 121843](https://github.com/XCharts-Team/XCharts/assets/70325881/9008aa06-f360-4161-b80c-29b3d10f66a1)
![Screenshot 2024-04-14 121859](https://github.com/XCharts-Team/XCharts/assets/70325881/714730fa-ab60-45dc-b178-9e550160e357)
![Screenshot 2024-04-14 121956](https://github.com/XCharts-Team/XCharts/assets/70325881/6a8c00a8-85ec-4b13-9df4-8afcadca8569)

</p>
</details> 
However, only first chart's DataZoom component work as intended. It could be zoomed in/out, and other charts also zoomed in/out together. But it's not possible from other charts, DataZoom component does not respond at all when dragging/scrolling etc. them.
Is it intended behavior? How to make them interconnected properly so that all charts can be zoomed in/out from set indexes?

For now i removed additional DataZoom components except for single, and changed your code a little, but i don't want to change base code too much, because it will cause me problems when updating XCharts to newer versions.

```c#
        public GridCoord GetGridOfDataZoom(DataZoom dataZoom)
        {
            GridCoord grid = null;
            if (dataZoom.xAxisIndexs != null && dataZoom.xAxisIndexs.Count > 0)
            {
                //Edited code
                for (int i = 0; i < dataZoom.xAxisIndexs.Count; i++)
                {
                    var xAxis = GetChartComponent<XAxis>(dataZoom.xAxisIndexs[i]);
                    var tempGrid = GetChartComponent<GridCoord>(xAxis.gridIndex);
                    if (tempGrid.IsPointerEnter())
                    {
                        grid = tempGrid;
                        break;
                    }
                }

                //Old code
                //var xAxis = GetChartComponent<XAxis>(dataZoom.xAxisIndexs[0]);
                //grid = GetChartComponent<GridCoord>(xAxis.gridIndex);
            }
            else if (dataZoom.yAxisIndexs != null && dataZoom.yAxisIndexs.Count > 0)
            {
                //Edited code
                for (int i = 0; i < dataZoom.yAxisIndexs.Count; i++)
                {
                    var yAxis = GetChartComponent<YAxis>(dataZoom.yAxisIndexs[i]);
                    var tempGrid = GetChartComponent<GridCoord>(yAxis.gridIndex);
                    if (tempGrid.IsPointerEnter())
                    {
                        grid = tempGrid;
                        break;
                    }
                }

                //Old code
                //var yAxis = GetChartComponent<YAxis>(dataZoom.yAxisIndexs[0]);
                //grid = GetChartComponent<GridCoord>(yAxis.gridIndex);
            }
            if (grid == null) return GetChartComponent<GridCoord>();
            else return grid;
        }
```

**Comment by monitor1394** [comment]
I believe that your optimized code will work well, and if it's convenient for you, you should consider submitting it for a Pull Request (PR).
