### ISSUE TITLE
Rebuild Chart Object have NullReferenceException

### ISSUE THREAD

**Issue by OopsAngela** [XCharts-Team/XCharts#321]
check  "Rebuild Chart Object" button ,Console show :NullReferenceException: Object reference not set to an instance of an object,what happened ?
![Snipaste_2024-05-13_18-04-44](https://github.com/XCharts-Team/XCharts/assets/148047049/3b581263-7df4-4b89-9983-a01cae68ee43)

**Comment by monitor1394** [comment]
check your tmp font asset setting
