### ISSUE TITLE
Code error：linechart.AddSerie<Line>("line")

### ISSUE THREAD

**Issue by DHBAT** [XCharts-Team/XCharts#324]
Refer to the provided XCharts tutorial: Get started with XCharts in 5 minutes. When using the code "**linechart.AddSerie<Line>("line")**;", an error occurs. The error message is: **Type "Line" cannot be used as type parameter "T" in generic type or method "BaseChart.AddSerie<T>(string,bool,bool)". There is no implicit reference conversion from "Line" to "XCharts.Runtime.Serie"**. How can I solve this problem? Here is my complete screenshot:
![code_error](https://github.com/user-attachments/assets/c28dc639-d48c-49c0-89d3-30ff27282505)
![completeCode](https://github.com/user-attachments/assets/19394700-b0c8-4731-a09e-959901aaeb18)

**Comment by DHBAT** [comment]
> Refer to the provided XCharts tutorial: Get started with XCharts in 5 minutes. When using the code "**linechart.AddSerie("line")**;", an error occurs. The error message is: **Type "Line" cannot be used as type parameter "T" in generic type or method "BaseChart.AddSerie(string,bool,bool)". There is no implicit reference conversion from "Line" to "XCharts.Runtime.Serie"**. How can I solve this problem? Here is my complete screenshot: ![code_error](https://private-user-images.githubusercontent.com/115906484/348155660-c28dc639-d48c-49c0-89d3-30ff27282505.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3Njc2NzksIm5iZiI6MTcyMDc2NzM3OSwicGF0aCI6Ii8xMTU5MDY0ODQvMzQ4MTU1NjYwLWMyOGRjNjM5LWQ0OGMtNDljMC04OWQzLTMwZmYyNzI4MjUwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwNjU2MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZmZlMTQwNTRjMjc3YjcwZTY0ZTkxZjdmNThhZWFhNGIzMzI4ODM4YWYyMThiNGEzOTczNzViOTFhMDExMzNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-JsoSx5SHyauY1DfNIrf8tIY3VbPIvPCfbGpBEm0G_o) ![completeCode](https://private-user-images.githubusercontent.com/115906484/348156122-19394700-b0c8-4731-a09e-959901aaeb18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3Njc2NzksIm5iZiI6MTcyMDc2NzM3OSwicGF0aCI6Ii8xMTU5MDY0ODQvMzQ4MTU2MTIyLTE5Mzk0NzAwLWIwYzgtNDczMS1hMDllLTk1OTkwMWFhZWIxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwNjU2MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmY0MmIxZjJhMzMyZDBkN2IzNWExNzhmNjI2ZTc5NTdlMDU1NzQ4MDQ4OTgyNTI1N2VlYmViNjQ0ZWYxZTcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZLCYeiEV95hJMZKMxOBet2-rvVHayGpkvfbdjfm7DFo)

![error_message](https://github.com/user-attachments/assets/d2cb8ad1-9d60-4b3c-9029-2b6a3112a5f6)

**Comment by monitor1394** [comment]
XCharts 2.x

> chart.AddSerie(SerieType.Line, "Line");

XCharts 3.x

> chart.AddSerie<Line>("Line");

You might need to confirm which version of XCharts you are currently using.
