### ISSUE TITLE
在微信小游戏中无法正常显示的问题

### ISSUE THREAD

**Issue by magikarpD** [XCharts-Team/XCharts#326]
在Unity editor中是这样的
![屏幕截图 2024-07-25 160555](https://github.com/user-attachments/assets/2e0b4693-4b9c-422d-ac5f-913757a86ad9)
在微信小游戏中就无法显示了，是没有适配吗？
![微信图片_20240725160806](https://github.com/user-attachments/assets/ade5ab86-596e-4056-bb76-089fa0c797cd)

**Comment by monitor1394** [comment]
应该是没有成功添加数据（看serie的name和x轴），先自查一下看看

**Comment by monitor1394** [comment]
应该是没有成功添加数据（看serie的name和x轴），先自查一下看看

**Comment by magikarpD** [comment]
我在Unity  editor中是没有任何问题的，打包到微信小游戏后将无法显示了，应该是对微信的适配有问题，因为我在微信开发者工具的控制台看到了这个
![屏幕截图 2024-07-29 120229](https://github.com/user-attachments/assets/443967ab-a53c-4a5d-a901-4a90da01aef0)

**Comment by magikarpD** [comment]
这个报错非常早，在项目刚打开就报了，我想知道以前有人成功在微信小游戏或者小程序使用过这个吗？如果有人成功过可能是我打包有问题。

**Comment by magikarpD** [comment]
这个报错非常早，在项目刚打开就报了，我想知道以前有人成功在微信小游戏平台使用过这个吗？如果有人成功过可能是我打包有问题。

**Comment by magikarpD** [comment]
这个报错非常早，在项目刚运行就报了，我想知道以前有人成功在微信小游戏平台使用过这个吗？如果有人成功过可能是我打包有问题。

**Comment by monitor1394** [comment]
> 我在Unity editor中是没有任何问题的，打包到微信小游戏后将无法显示了，应该是对微信的适配有问题，因为我在微信开发者工具的控制台看到了这个 ![屏幕截图 2024-07-29 120229](https://private-user-images.githubusercontent.com/70927203/352910477-443967ab-a53c-4a5d-a901-4a90da01aef0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjQ5NzYsIm5iZiI6MTcyMjI2NDY3NiwicGF0aCI6Ii83MDkyNzIwMy8zNTI5MTA0NzctNDQzOTY3YWItYTUzYy00YTVkLWE5MDEtNGE5MGRhMDFhZWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE0NTExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MmNlMzcwMzI4ZDc2YTFhYTYyOTE4ODJiOWRiZWVkNjI5NjdhNjBmNGM0NGU4MDc3ZGFmMWU2NWFmMWQ0YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I97o2JlPsKJdQzbxE3_6nsl9ImrMp7dE-k6oQDYCDX0)

这个信息很有帮助，兼容问题已在master分支处理提交了。
后续发现在微信小游戏平台上的一些问题也欢迎反馈。
