### ISSUE TITLE
Animation Enable/Disable

### ISSUE THREAD

**Issue by melcherJustin** [XCharts-Team/XCharts#334]
https://github.com/XCharts-Team/XCharts/blob/7fb0765c6cae19e8e1991b65099ff704f30acad2/Runtime/Serie/Serie.cs#L2008C1-L2012C10

Hello! This if statement prevents me from enabling the Animation after I have disabled it once. This doesn't seem like desirable functionality. 

Thanks for the great code, by the way!

**Comment by monitor1394** [comment]
Thank you for your feedback. This code does have issues, and the master branch has already been fixed.

**Comment by melcherJustin** [comment]
Thank you!
