### ISSUE TITLE
Problem of maxCache

### ISSUE THREAD

**Issue by lyylsh** [XCharts-Team/XCharts#335]
When I use Chart.SetMaxCache() for line chart. I found that the data will not change dynamically after reaching the value set by maxcache.How can I deal with it. Thank u.

**Comment by monitor1394** [comment]
How did you add the data? Could you show the relevant code?

**Comment by lyylsh** [comment]
> How did you add the data? Could you show the relevant code?
Just like this. Implemented in a loop within a thread.

 eyeQueue.TryDequeue(out eyeData);
 dataChart.AddXAxisData("x" + cnt);
 dataChart.AddData(0, eyeData);

![0a140c9864b87fce0137ae1d6757dd0](https://github.com/user-attachments/assets/709f2a28-65ed-458c-8d0a-df813f434ed0)

**Comment by monitor1394** [comment]
The code seems fine. If you called `dataChart.SetMaxCache` before `StartServer`, it should work as expected. Could you provide more details? What version of XCharts are you using?

**Comment by lyylsh** [comment]
> 代码似乎很好。如果您之前致电，它应该会按预期工作。你能否介绍有关情况？您使用的是哪个版本的 XCharts？`dataChart.SetMaxCache``StartServer`

I've just realized that it may have been an issue due to the ignore break I had set, I kept updating the index of the x-axis causing the array to go out of bounds. It's fixed now, thanks.

**Comment by lyylsh** [comment]
> The code seems fine. If you called `dataChart.SetMaxCache` before `StartServer`, it should work as expected. Could you provide more details? What version of XCharts are you using?

I've just realized that it may have been an issue due to the ignore break I had set, I kept updating the index of the x-axis causing the array to go out of bounds. It's fixed now, thanks.
