### ISSUE TITLE
piechart的label重叠

### ISSUE THREAD

**Issue by moonforce** [XCharts-Team/XCharts#56]
数值非常接近时，会出现label重叠现象

**Comment by monitor1394** [comment]
Serie加了avoidLabelOverlap参数，具体用法请看配置项手册。

**Comment by moonforce** [comment]
> Serie加了avoidLabelOverlap参数，具体用法请看配置项手册。
效果不算太好，如下图，是否可参考echarts的做法。
![image](https://user-images.githubusercontent.com/10993776/84866388-39defd00-b0ac-11ea-8302-802809cbb753.png)

**Comment by peerless2012** [comment]
使用这个参数后，还是有问题。
在编辑状态下，有的时候能错开，有的时候还是叠在一起，运行时一直都叠在一起。
![QQ截图20200828172042](https://user-images.githubusercontent.com/3116469/91546049-75bbfb80-e954-11ea-9b6f-2edd0807989f.jpg)
![QQ截图20200828172121](https://user-images.githubusercontent.com/3116469/91546067-7eaccd00-e954-11ea-9f24-2153da6fdb59.jpg)

**Comment by monitor1394** [comment]
> 使用这个参数后，还是有问题。
> 在编辑状态下，有的时候能错开，有的时候还是叠在一起，运行时一直都叠在一起。
> ![QQ截图20200828172042](https://user-images.githubusercontent.com/3116469/91546049-75bbfb80-e954-11ea-9b6f-2edd0807989f.jpg)
> ![QQ截图20200828172121](https://user-images.githubusercontent.com/3116469/91546067-7eaccd00-e954-11ea-9f24-2153da6fdb59.jpg)

用最新版本

**Comment by peerless2012** [comment]
> > 使用这个参数后，还是有问题。
> > 在编辑状态下，有的时候能错开，有的时候还是叠在一起，运行时一直都叠在一起。
> > ![QQ截图20200828172042](https://user-images.githubusercontent.com/3116469/91546049-75bbfb80-e954-11ea-9b6f-2edd0807989f.jpg)
> > ![QQ截图20200828172121](https://user-images.githubusercontent.com/3116469/91546067-7eaccd00-e954-11ea-9f24-2153da6fdb59.jpg)
> 
> 用最新版本

使用1.6.0仍旧有这个问题。如果两个项目都是0，那么这两个仍然会重叠。

**Comment by monitor1394** [comment]
我在unity2017上自测正常，清确认下是否勾选了AvoidLabelOverlap。或者给重现步骤，如果是unity2019版本，可以导出preset文件给我测试下。

**Comment by peerless2012** [comment]
> 我在unity2017上自测正常，清确认下是否勾选了AvoidLabelOverlap。或者给重现步骤，如果是unity2019版本，可以导出preset文件给我测试下。

我这边测试是第一次设置两个0会重叠，后面再出现重复的就不会重叠了。
[FinishPieChart.zip](https://github.com/monitor1394/unity-ugui-XCharts/files/5274851/FinishPieChart.zip)

**Comment by peerless2012** [comment]
Any updates？

**Comment by monitor1394** [comment]
> > 我在unity2017上自测正常，清确认下是否勾选了AvoidLabelOverlap。或者给重现步骤，如果是unity2019版本，可以导出preset文件给我测试下。
> 
> 我这边测试是第一次设置两个0会重叠，后面再出现重复的就不会重叠了。
> [FinishPieChart.zip](https://github.com/monitor1394/unity-ugui-XCharts/files/5274851/FinishPieChart.zip)

我在unity2019.4.13f1上测试了你给的prefab，正常，没有出现过你说的问题。

**Comment by peerless2012** [comment]
> > > 我在unity2017上自测正常，清确认下是否勾选了AvoidLabelOverlap。或者给重现步骤，如果是unity2019版本，可以导出preset文件给我测试下。
> > 
> > 
> > 我这边测试是第一次设置两个0会重叠，后面再出现重复的就不会重叠了。
> > [FinishPieChart.zip](https://github.com/monitor1394/unity-ugui-XCharts/files/5274851/FinishPieChart.zip)
> 
> 我在unity2019.4.13f1上测试了你给的prefab，正常，没有出现过你说的问题。

是否测试三组数据，第1、2组是0，第3组100？

**Comment by monitor1394** [comment]
是的。你用的unity什么版本，不行你加Q群录个视频吧。

**Comment by peerless2012** [comment]
> 是的。你用的unity什么版本，不行你加Q群录个视频吧。

OK

**Comment by yu-xiaowen** [comment]
`using UnityEngine;
using XCharts;

public class TestOverlap : MonoBehaviour
{
    public PieChart aPieChart;

    void Start()
    {
        initAPieChart();
    }

    void initAPieChart()
    {
        aPieChart.ClearData();
        aPieChart.AddData(0, 105, "数据1");
        aPieChart.AddData(0, 13, "数据2");
        aPieChart.AddData(0, 3, "测试数据3");
        aPieChart.AddData(0, 5, "我的测试数据数据4");
        aPieChart.AddData(0, 11, "数据5");
        aPieChart.AddData(0, 52, "数据6");
        aPieChart.AddData(0, 120, "数据7");

        aPieChart.legend.show = false;
        aPieChart.rectTransform.sizeDelta = new Vector2(1000, 800);
        aPieChart.series.GetSerie(0).center = new float[2] { 0.5f, 0.5f };
        aPieChart.series.GetSerie(0).radius = new float[2] { 0f, 170f };
        aPieChart.series.GetSerie(0).avoidLabelOverlap = true;
        aPieChart.series.GetSerie(0).label.show = true;
        aPieChart.series.GetSerie(0).label.line = true;
        aPieChart.series.GetSerie(0).label.lineLength1 = 70;
        aPieChart.series.GetSerie(0).label.lineLength2 = 50;
        aPieChart.series.GetSerie(0).label.textStyle.alignment = TextAnchor.MiddleLeft;
        aPieChart.series.GetSerie(0).label.textStyle.fontSize = 30;
        aPieChart.series.GetSerie(0).label.formatter =
            "<color=\"#666600\">{b}</color>\n<b><size=50>{c}人</size></b>";

        aPieChart.RefreshLabel();
        aPieChart.RefreshChart();
    }
}`

aPieChart.series.GetSerie(0).label.formatter 设置格式后，还是会重叠。设置格式的代码注释掉也有点小问题。
![饼图标签带格式](https://user-images.githubusercontent.com/12179755/119470070-8a5de080-bd7a-11eb-88fa-c141051e8e76.png)
![饼图标签](https://user-images.githubusercontent.com/12179755/119470092-9053c180-bd7a-11eb-906f-2f812d519d3d.png)

**Comment by liqq89998** [comment]
> 

大佬qq群号多少

**Comment by monitor1394** [comment]
readme上有的

**Comment by monitor1394** [comment]
v3.1.0版本已优化。
